package schema

func GetFields(name string) []string {
	var fields = map[string][]string{
		"ActionRemark": []string{
			"archive",
			"remark",
		},
		"Address": []string{
			"building_name",
			"building_number",
			"city",
			"country",
			"county",
			"line_1",
			"line_2",
			"months_at_address",
			"postcode",
		},
		"Analytics": []string{
			"utms",
		},
		"ApiEvent": []string{
			"action",
			"comm_context",
			"error",
			"method",
			"resource",
			"resource_data",
			"resource_id",
		},
		"ApplicantDetails": []string{
			"additional_employment_details",
			"bank_account",
			"customer_details",
			"employment_details",
			"finance_details",
		},
		"Approval": []string{
			"outcome",
			"reason",
			"reason_note",
		},
		"Audit": []string{
			"aid",
			"bid",
			"cid",
			"current_action_state",
			"eid",
			"entries",
			"id",
			"metadata",
			"oid",
			"resource_id",
			"resources",
			"tid",
		},
		"AuditInput": []string{
			"action_state",
			"assignee_email",
			"note",
			"resource",
			"resource_id",
		},
		"AuthUser": []string{
			"audience",
			"authorisation_url",
			"bid",
			"branches",
			"cid",
			"departments",
			"disabled",
			"eid",
			"email",
			"groups",
			"id",
			"issuer",
			"name",
			"phone",
			"photoURL",
			"provider",
			"role",
			"subject",
			"token",
			"verified",
		},
		"BankAccount": []string{
			"account_name",
			"account_number",
			"months_held",
			"sort_code",
		},
		"BaseId": []string{
			"aid",
			"bid",
			"cid",
			"eid",
			"id",
			"metadata",
			"oid",
			"tid",
		},
		"Branding": []string{
			"logo",
		},
		"Budgets": []string{
			"max",
			"min",
		},
		"BusinessConfig": []string{
			"business_sector",
			"extra",
			"lender",
			"lender_rate_type",
			"show",
			"trade_text",
			"trade_type",
		},
		"Cache": []string{
			"cid",
			"id",
			"metadata",
			"oid",
		},
		"Campaign": []string{
			"aid",
			"bid",
			"cid",
			"eid",
			"event_name",
			"gclid",
			"id",
			"metadata",
			"oid",
			"referrer",
			"sid",
			"utm",
		},
		"Category": []string{
			"number_of_correct_quizzes",
			"number_of_quizzes",
			"result",
			"section",
		},
		"CommContext": []string{
			"bank_account",
			"cta_sub_url",
			"cta_url",
			"deposit",
			"documents",
			"extras",
			"flow_type",
			"lender",
			"message",
			"receiver",
			"reference",
			"sender",
			"subdomain",
			"template",
			"template_name",
		},
		"CommExtras": []string{
			"branch",
			"customer",
			"trader",
		},
		"CommPreferences": []string{
			"other",
			"post_job",
			"pre_job",
		},
		"Company": []string{
			"aid",
			"analytics",
			"bank_account",
			"billing",
			"business_config",
			"business_type",
			"cid",
			"company_info",
			"company_logo",
			"company_type",
			"contact_info",
			"emails",
			"fca_number",
			"finance_rates",
			"id",
			"lender_configs",
			"lifecycle",
			"limited_company_info",
			"metadata",
			"oid",
			"quote_preference",
			"redirect_urls",
			"referral_activated_at",
			"referral_code",
			"referred_by",
			"skip_deposit",
			"solar_company_info",
			"sole_trader_info",
			"tier_config",
			"training_status",
			"users",
			"welcome_pack",
		},
		"CompanyDirectorReport": []string{
			"current_appointment_ccj",
			"director_name",
			"disqualified",
			"inactive_appointment_ccj",
			"number_of_current_appointments",
			"number_of_inactive_appointments",
			"number_of_previous_appointments",
			"people_id",
			"previous_appointment_ccj",
		},
		"CompanyInfo": []string{
			"average_job_value",
			"average_monthly_jobs",
			"contract_agreement",
			"insurance_document",
			"online_presence",
			"trade_body",
			"trade_body_name",
			"trade_body_number",
			"trade_type",
			"trade_type_name",
			"use_subcontractor",
			"warranty_length",
			"work_types",
		},
		"CompanyReport": []string{
			"active_ccj_exact",
			"active_ccj_possible",
			"credit_limit",
			"incorporation_date",
			"number_of_writs",
			"people_ids",
			"report_pdf",
			"risk_score",
			"satisfied_ccj",
			"status",
		},
		"ConsumerReport": []string{
			"active_ccj",
			"credit_score",
			"credit_score_band",
			"insolvencies",
			"satisfied_ccj",
		},
		"ConsumerSignature": []string{
			"pre_application_declarations",
			"signature",
		},
		"ContactInfo": []string{
			"contact_address",
			"contact_email",
			"contact_name",
			"contact_phone",
			"trading_name",
		},
		"ContractAgreement": []string{
			"agreed_terms_and_conditions",
			"agreed_to_become_iar_of_kanda",
			"contract",
			"print_name",
			"signed_at",
		},
		"Credit": []string{
			"additional_employment_details",
			"aid",
			"amount",
			"bank_account",
			"bid",
			"cid",
			"credit_documents",
			"customer_details",
			"deposit_value",
			"eid",
			"employment_details",
			"extra_applicants",
			"finance_details",
			"finance_option",
			"flow_type",
			"id",
			"introduced_to",
			"kid",
			"kind",
			"metadata",
			"oid",
			"provider",
			"quoted_to",
			"signature",
			"state",
			"tid",
			"xid",
			"xref",
			"xstatus",
		},
		"Customer": []string{
			"address",
			"email",
			"first_name",
			"last_name",
			"phone",
		},
		"CustomerDetails": []string{
			"current_address",
			"date_of_birth",
			"email",
			"first_name",
			"gender",
			"goods_delivery_address",
			"last_name",
			"maiden_name",
			"marital_status",
			"middle_name",
			"mobile",
			"monthly_rent_amount",
			"number_of_dependants",
			"previous_address_one",
			"previous_address_two",
			"residential_status",
			"telephone",
			"title",
		},
		"CustomerOptions": []string{
			"agree_commission_terms",
			"checkout_option",
			"deposit_value",
			"finance_option",
		},
		"DirectorInfo": []string{
			"date_of_birth",
			"home_address",
			"verification_status",
		},
		"DirectorVerification": []string{
			"date_of_birth",
			"email",
			"first_name",
			"home_address",
			"last_name",
			"mobile",
		},
		"Document": []string{
			"aid",
			"bid",
			"cid",
			"content",
			"eid",
			"expiry",
			"id",
			"metadata",
			"mimetype",
			"name",
			"oid",
			"tid",
		},
		"EmployedDetails": []string{
			"employed_type",
			"employer_address",
			"employer_name",
			"main_occupation",
			"months_employed",
		},
		"EmploymentDetails": []string{
			"employed_details",
			"employment_status",
			"gross_annual_income",
			"household_annual_income",
			"not_employed_details",
			"retired_details",
			"self_employed_details",
		},
		"Enquiry": []string{
			"aid",
			"archived",
			"bid",
			"cid",
			"current_state",
			"eid",
			"enquiry_info",
			"id",
			"metadata",
			"name",
			"oid",
			"source",
			"states",
			"tid",
		},
		"EnquiryBody": []string{
			"enquiry_info",
			"name",
			"source",
		},
		"EnquiryInfo": []string{
			"budget",
			"consumer",
			"consumer_signature",
			"interest_in_credit",
			"job_info",
		},
		"EnquiryStateRequest": []string{
			"state",
		},
		"Enrolment": []string{
			"aid",
			"bid",
			"cid",
			"eid",
			"id",
			"metadata",
			"oid",
			"rate_request",
			"tid",
		},
		"Enterprise": []string{
			"aid",
			"bid",
			"branch_code",
			"branding",
			"cid",
			"contact_info",
			"eid",
			"emails",
			"enterprise_type",
			"id",
			"lender_configs",
			"metadata",
			"oid",
			"subdomain",
			"users",
		},
		"EnterpriseUserRole": []string{
			"bid",
			"branches",
			"departments",
			"eid",
			"email",
			"groups",
			"id",
			"role",
		},
		"EnterpriseUserType": []string{
			"comm_preferences",
			"email",
			"mobile",
			"name",
			"role",
			"uid",
		},
		"Entry": []string{
			"action_state",
			"assignee_email",
			"assignee_name",
			"note",
			"owner_email",
			"owner_name",
			"resource",
			"resource_id",
			"timestamp",
		},
		"Error": []string{
			"code",
			"message",
		},
		"Event": []string{
			"event_options",
			"event_props",
			"name",
			"purchase",
		},
		"EventOptions": []string{
			"device_id",
			"ip",
			"session_id",
			"time",
			"user_id",
		},
		"EventProps": []string{
			"api",
			"domain",
			"element",
			"element_id",
			"element_path",
			"info",
			"params",
			"path",
			"referrer",
			"request_user",
			"url",
			"user_agent",
		},
		"Expenditure": []string{
			"expenditure_type",
			"monthly_amount",
		},
		"ExportCSV": []string{
			"csv",
		},
		"ExportJSON": []string{},
		"FinanceDetails": []string{
			"bankrupcy_or_iva_in_last_5_years",
			"expenditures",
			"incomes",
		},
		"FinanceRate": []string{
			"apr",
			"apr_type",
			"charge",
			"credit_line",
			"deferred_duration",
			"duration",
			"enabled",
			"fee",
			"finance_types",
			"max_deposit_pct",
			"max_deposit_value",
			"max_job_value",
			"min_charge",
			"min_deposit_pct",
			"min_deposit_value",
			"min_job_value",
			"name",
			"provider",
			"work_types",
		},
		"Flag": []string{
			"aid",
			"flagged_at",
			"level",
			"remark",
		},
		"Income": []string{
			"income_type",
			"income_type_info",
			"monthly_amount",
		},
		"InfoAuth": []string{
			"continue_url",
			"email",
		},
		"InfoCheckoutRedirect": []string{
			"aid",
			"bid",
			"checkout_options",
			"cid",
			"customer",
			"deposit_type",
			"deposit_value",
			"eid",
			"enabled_rates",
			"flow_type",
			"id",
			"job_items",
			"metadata",
			"oid",
			"redirect_urls",
			"reference",
			"tid",
			"work_type",
		},
		"InfoCompany": []string{
			"directors",
			"id",
			"limited_company",
			"metadata",
			"sole_trader",
		},
		"InfoEnquiry": []string{
			"branding",
			"contact_info",
			"enquiry",
		},
		"InfoEntity": []string{
			"company",
			"credit",
			"introduction",
			"job",
			"monitor",
			"onboarding",
			"payment",
		},
		"InfoGhost": []string{
			"bearer_token",
			"custom_role",
			"custom_token",
			"email",
		},
		"InfoIP": []string{
			"ipv4",
		},
		"InfoIntroductionStats": []string{
			"report",
		},
		"InfoLead": []string{
			"contact_info",
			"flow_type",
			"id",
		},
		"InfoLegacyRedirect": []string{
			"aid",
			"bid",
			"cid",
			"deposit",
			"description_of_goods",
			"eid",
			"email",
			"enabled_rates",
			"enterprise_id",
			"first_name",
			"id",
			"last_name",
			"metadata",
			"mobile",
			"oid",
			"price",
			"redirect_urls",
			"reference",
			"tid",
			"work_type",
		},
		"InfoMe": []string{
			"email",
			"name",
			"phone",
			"photoURL",
			"referrer",
		},
		"InfoOnboarding": []string{
			"cid",
			"current_approval",
			"current_stage",
			"id",
			"metadata",
		},
		"InfoPartnerBranding": []string{
			"branding",
			"contact_info",
			"id",
		},
		"InfoQuery": []string{
			"query",
			"result",
		},
		"InfoRelation": []string{
			"aid",
			"bid",
			"branches",
			"cid",
			"departments",
			"eid",
			"groups",
			"id",
			"metadata",
			"oid",
		},
		"InfoSearch": []string{
			"filter",
			"hits",
			"index",
			"limit",
			"offset",
			"q",
			"sort",
			"total",
		},
		"InfoSession": []string{
			"code",
			"custom_token",
		},
		"InfoStats": []string{
			"id",
			"jobs_applied_for_finance",
			"jobs_approval_rate",
			"jobs_approved_for_finance",
			"jobs_average_value_of_approved",
			"jobs_sent",
			"jobs_total_revenue_of_approved",
		},
		"InfoTag": []string{
			"name",
			"xurl",
		},
		"InfoTrade": []string{
			"address",
			"lat_lng",
		},
		"InfoValidationEmail": []string{
			"email",
			"source",
			"suggestion",
			"verdict",
		},
		"InfoWorkType": []string{
			"primary",
			"product",
			"rates",
			"work_type",
		},
		"InterestInCreditRequest": []string{
			"interest_in_credit",
		},
		"Introduction": []string{
			"aid",
			"archived",
			"bid",
			"budgets",
			"cid",
			"consumer",
			"consumer_details",
			"consumer_signature",
			"current_state",
			"eid",
			"flow_type",
			"id",
			"job_details",
			"metadata",
			"oid",
			"remark",
			"states",
			"tid",
			"trader",
			"trader_details",
			"trader_signature",
			"xid",
			"xref",
		},
		"IntroductionStateRequest": []string{
			"state",
		},
		"IntroductionStats": []string{
			"approval_rate",
			"approve_applications",
			"average_job_value",
			"average_order_value",
			"branch_code",
			"branch_name",
			"finance_applications",
			"introductions_completed",
			"introductions_sent",
			"job_revenue",
			"order_details_added",
			"potential_revenue",
			"total_revenue",
			"tradesperson_approved",
		},
		"Job": []string{
			"aid",
			"archived",
			"bid",
			"checkout_options",
			"cid",
			"customer",
			"customer_options",
			"deposit_type",
			"deposit_value",
			"description",
			"eid",
			"finance_options",
			"finance_status",
			"flow_type",
			"id",
			"introduced_to",
			"job_documents",
			"job_items",
			"job_type",
			"metadata",
			"metarefs",
			"notes",
			"oid",
			"payments",
			"quoted_to",
			"redirect_urls",
			"sat_note",
			"sat_note_timeline",
			"status",
			"tid",
			"title",
			"total",
			"work_type",
			"xid",
			"xref",
		},
		"JobCompanyInfo": []string{
			"bank_account",
			"company_logo",
			"company_name",
			"contact_info",
			"id",
			"vat_number",
		},
		"JobCreditState": []string{
			"current_status",
			"has_finance_application",
			"id",
			"xstatus",
		},
		"JobDetails": []string{
			"description",
			"items",
			"metarefs",
			"reference",
			"total",
		},
		"JobInfo": []string{
			"job_items",
			"quote",
			"work_type",
		},
		"JobItem": []string{
			"description",
			"price",
			"quantity",
			"quote_document",
			"style",
			"title",
			"vat",
			"vat_rate",
		},
		"JobOverride": []string{
			"action",
			"customer_options",
			"xref",
		},
		"LatLng": []string{
			"lat",
			"lng",
		},
		"Lead": []string{
			"accepted",
			"aid",
			"bid",
			"budget",
			"cid",
			"connected",
			"eid",
			"expired_at",
			"finance_options",
			"flow_type",
			"id",
			"invite_info",
			"lead_applicant",
			"lead_quote",
			"lead_trade",
			"max_credit_amount",
			"metadata",
			"oid",
			"referrer",
			"source",
			"status",
			"tid",
			"xid",
			"xref",
		},
		"LeadApplicant": []string{
			"additional_employment_details",
			"bank_account",
			"budget",
			"customer_details",
			"employment_details",
			"extra_applicants",
			"finance_details",
		},
		"LeadJobSummary": []string{
			"aid",
			"archived",
			"bid",
			"cid",
			"eid",
			"finance_status",
			"id",
			"oid",
			"quoted_to",
			"rid",
			"status",
			"tid",
			"total",
		},
		"LeadQuote": []string{
			"deposit",
			"description",
			"finance_option",
			"job_items",
			"reference",
			"total",
			"work_finished_by",
			"work_type",
		},
		"LeadTrade": []string{
			"address",
			"email",
			"mobile",
			"trading_name",
		},
		"LenderConfig": []string{
			"provider",
			"xid",
		},
		"LenderImport": []string{
			"cid",
			"fca_number",
			"ibc_ref",
		},
		"LimitedCompanyInfo": []string{
			"company_address",
			"company_name",
			"company_number",
			"trading_address",
			"vat_number",
		},
		"Metadata": []string{
			"created_at",
			"liveness",
			"updated_at",
		},
		"Metarefs": []string{
			"references",
		},
		"Money": []string{
			"amount",
			"currency",
		},
		"MoneyTotal": []string{
			"amount_vat",
			"amount_vat_exclusive",
			"amount_vat_inclusive",
		},
		"Monitor": []string{
			"flag",
			"flags",
			"id",
			"metadata",
		},
		"NotEmployedDetails": []string{
			"months_not_employed",
			"source_of_income",
		},
		"Onboarding": []string{
			"aid",
			"cid",
			"company_review",
			"consumer_review",
			"current_stage",
			"director_review",
			"fca_awaiting_approval",
			"fca_upload",
			"id",
			"insurance_review",
			"metadata",
			"oid",
			"online_review",
			"owner_review",
			"shared_note",
			"stages",
			"trade_review",
		},
		"OnlinePresence": []string{
			"facebook",
			"google",
			"q_online",
			"website",
		},
		"OwnerReport": []string{
			"adverse_media",
			"edited_electoral_roll",
			"enhanced_international_saction_warnings",
			"international_sanctions_warnings",
			"national_id_register",
			"overall_pass",
			"uk_credit_aml_warnings",
			"uk_credit_header",
		},
		"Partner": []string{
			"aid",
			"branding",
			"cids",
			"contact_info",
			"current_reward",
			"emails",
			"id",
			"metadata",
			"oid",
			"referrals",
			"rewards",
			"stats",
		},
		"Payment": []string{
			"aid",
			"bid",
			"cid",
			"eid",
			"flow_type",
			"id",
			"introduced_to",
			"kid",
			"kind",
			"metadata",
			"oid",
			"payment_option",
			"quoted_to",
			"status",
			"tid",
			"xid",
			"xref",
		},
		"PaymentOption": []string{
			"amount",
			"payment_method",
			"provider",
		},
		"PurchaseEvent": []string{
			"kid",
			"kind",
			"payment",
			"pid",
		},
		"Quiz": []string{
			"answers",
			"category",
			"correct_answer",
			"question",
			"user_answer",
			"videoId",
		},
		"Rate": []string{
			"finance_rates",
			"id",
			"metadata",
		},
		"RateRequest": []string{
			"added",
			"metadata",
			"removed",
			"requester",
			"to_add",
			"to_remove",
		},
		"RedirectURLs": []string{
			"checkout_url",
			"failure_url",
			"success_url",
			"webhook_url",
		},
		"Referral": []string{
			"billing",
			"cid",
			"email",
			"from",
			"lifecycle",
			"metadata",
			"mobile",
			"name",
			"trading_name",
		},
		"RetiredDetails": []string{
			"months_retired",
		},
		"Reward": []string{
			"activations",
			"name",
			"rates_reduction_pct",
			"rates_reduction_value",
			"referral_commission_pct",
			"referral_commission_value",
			"signups",
			"subscribers",
			"verifications",
		},
		"SatNote": []string{
			"certificate",
			"q_advice",
			"q_application",
			"q_availability",
			"q_easiness",
			"q_pressure",
			"q_rate",
			"q_saving",
			"signature",
		},
		"SatNoteTimeline": []string{
			"sent_at",
			"signed_at",
			"viewed_at",
		},
		"SearchHits": []string{
			"audit",
			"audit_hits",
			"audit_returned",
			"company",
			"company_hits",
			"company_returned",
			"credit",
			"credit_hits",
			"credit_returned",
			"enterprise",
			"enterprise_hits",
			"enterprise_returned",
			"introduction",
			"introduction_hits",
			"introduction_returned",
			"job",
			"job_hits",
			"job_returned",
			"onboarding",
			"onboarding_hits",
			"onboarding_returned",
			"transaction",
			"transaction_hits",
			"transaction_returned",
		},
		"SelfEmployedDetails": []string{
			"business_address",
			"business_name",
			"months_self_employed",
			"self_employed_type",
			"type_of_business",
		},
		"SignDocument": []string{
			"quote",
			"signature",
		},
		"Signature": []string{
			"fingerprint",
			"signed",
		},
		"SolarCompanyInfo": []string{
			"electrical_trade_association",
			"electrical_trade_association_number",
			"epvs_registration_number",
			"solar_trade_association",
			"solar_trade_association_number",
		},
		"SoleTraderInfo": []string{
			"national_insurance_number",
			"trading_address",
			"trading_name",
			"vat_number",
		},
		"Subscription": []string{
			"aid",
			"amount",
			"authorisation_url",
			"billing",
			"billing_status",
			"cid",
			"day_of_month",
			"id",
			"interval",
			"mandate",
			"mandate_status",
			"metadata",
			"oid",
			"xid",
			"xref",
		},
		"Tag": []string{
			"aid",
			"bid",
			"cid",
			"eid",
			"id",
			"metadata",
			"name",
			"oid",
			"source",
			"tid",
			"xurl",
		},
		"TagBody": []string{
			"name",
			"source",
			"xurl",
		},
		"Tally": []string{
			"failure",
			"id",
		},
		"TierConfig": []string{
			"current_tier",
			"tiers",
		},
		"TierEvent": []string{
			"action",
			"actioned_at",
			"tier",
		},
		"TradeFilter": []string{
			"distance",
			"keyword",
			"work_types",
		},
		"TradeSummary": []string{
			"company_logo",
			"contact_info",
			"distance",
			"id",
			"lat_lng",
			"trading_type",
			"work_types",
		},
		"Trader": []string{
			"contact_email",
			"contact_mobile",
			"contact_name",
			"reference",
			"trading_address",
			"trading_name",
			"trading_type",
			"vat_number",
		},
		"TraderDetails": []string{
			"bank_account",
			"bank_report",
			"bank_type",
			"bank_verification",
			"company_type",
			"limited_company_info",
			"sole_trader_info",
		},
		"Training": []string{
			"aid",
			"bid",
			"categories",
			"cid",
			"eid",
			"id",
			"metadata",
			"oid",
			"quizzes",
			"result",
		},
		"Transaction": []string{
			"account_name",
			"amount",
			"fee",
			"id",
			"lender",
			"metadata",
			"note",
			"payout_date",
			"payout_type",
			"vat",
			"xid",
			"xref",
		},
		"UTM": []string{
			"utm_campaign",
			"utm_content",
			"utm_medium",
			"utm_source",
			"utm_term",
		},
		"UserEvent": []string{
			"cid",
			"email",
			"id",
			"mobile",
			"name",
			"provider",
			"role",
			"verified",
		},
		"UserType": []string{
			"comm_preferences",
			"director_info",
			"email",
			"first_name",
			"last_name",
			"mobile",
			"role",
		},
		"WelcomeSkipBanner": []string{
			"advert_finance_calculator",
			"director_verification",
			"invite_team_member",
			"update_website",
		},
	}

	existed, ok := fields[name]
	if ok {
		return existed
	}
	return []string{}
}

func GetAllWorkTypes() []WorkType {
	return []WorkType{
		WorkTypeAesthetics,
		WorkTypeAirConditioning,
		WorkTypeAirSourceHeatPumps,
		WorkTypeAlarmSystems,
		WorkTypeAppliances,
		WorkTypeArtificialGrass,
		WorkTypeBathroomsSupplyAndFitted,
		WorkTypeBathroomsSupplyOnly,
		WorkTypeBatteryStorage,
		WorkTypeBedroomsFurnitueCustom,
		WorkTypeBlindsAwningsShutters,
		WorkTypeBoilerSwap,
		WorkTypeCarBodyShop,
		WorkTypeCarDetailingAndAlloys,
		WorkTypeCarpentry,
		WorkTypeCatering,
		WorkTypeCctv,
		WorkTypeCentralHeatingSystem,
		WorkTypeComputerBuilder,
		WorkTypeConservatory,
		WorkTypeConservatoryRoof,
		WorkTypeDecking,
		WorkTypeDental,
		WorkTypeDoorCanopy,
		WorkTypeDoorInternal,
		WorkTypeDoors,
		WorkTypeDriveways,
		WorkTypeElectricalInstallation,
		WorkTypeElectronics,
		WorkTypeEntertainers,
		WorkTypeEvCharger,
		WorkTypeEvents,
		WorkTypeExperiences,
		WorkTypeFencing,
		WorkTypeFireplaces,
		WorkTypeFittedFurniture,
		WorkTypeFlooringExcludingCarpets,
		WorkTypeFlowers,
		WorkTypeFullEventsPackage,
		WorkTypeFurniture,
		WorkTypeGarageDoors,
		WorkTypeGardenBuildings,
		WorkTypeGates,
		WorkTypeGlassSplashBacks,
		WorkTypeGraniteWorktops,
		WorkTypeGraphicDesigner,
		WorkTypeGroundSourceHeatPumps,
		WorkTypeHighEndClothing,
		WorkTypeHomeLifts,
		WorkTypeHomeRemovals,
		WorkTypeHomeStudy,
		WorkTypeHotTubsAndSpas,
		WorkTypeInsulationRoofFoilWrapOnly,
		WorkTypeJewllery,
		WorkTypeKitchensFitted,
		WorkTypeKitchensSupplyOnly,
		WorkTypeLandscaping,
		WorkTypeLoftBoarding,
		WorkTypeLoftConversion,
		WorkTypeMediaWalls,
		WorkTypeMedicalAssessments,
		WorkTypeMemberships,
		WorkTypeMobillityAndMobilityScooters,
		WorkTypeNetworkEngineer,
		WorkTypeNumberPlates,
		WorkTypeOther,
		WorkTypePaintingAndDecorating,
		WorkTypePatios,
		WorkTypePersonalSecurity,
		WorkTypePhotography,
		WorkTypePlanners,
		WorkTypePlastering,
		WorkTypePorch,
		WorkTypeRendering,
		WorkTypeResinDriveways,
		WorkTypeRoofing,
		WorkTypeRoofingExclFlatRoofs,
		WorkTypeRoofline,
		WorkTypeSecurityLighting,
		WorkTypeSolarPvPanels,
		WorkTypeSportsEquipment,
		WorkTypeStairLifts,
		WorkTypeStaircases,
		WorkTypeTechnologyRepair,
		WorkTypeTiling,
		WorkTypeToolSales,
		WorkTypeTyres,
		WorkTypeUnderStairStorage,
		WorkTypeUnderfloorHeating,
		WorkTypeUpvcDoors,
		WorkTypeVehicleWrapping,
		WorkTypeVenues,
		WorkTypeVerandas,
		WorkTypeWallInsulationAndCladding,
		WorkTypeWardrobes,
		WorkTypeWaterSofteners,
		WorkTypeWebsiteBuilder,
		WorkTypeWindows,
		WorkTypeWindowsAndDoors,
	}
}

func GetAllWorkTypeStrings() []string {
	return []string{
		"aesthetics",
		"air_conditioning",
		"air_source_heat_pumps",
		"alarm_systems",
		"appliances",
		"artificial_grass",
		"bathrooms_supply_and_fitted",
		"bathrooms_supply_only",
		"battery_storage",
		"bedrooms_furnitue_custom",
		"blinds_awnings_shutters",
		"boiler_swap",
		"car_body_shop",
		"car_detailing_and_alloys",
		"carpentry",
		"catering",
		"cctv",
		"central_heating_system",
		"computer_builder",
		"conservatory",
		"conservatory_roof",
		"decking",
		"dental",
		"door_canopy",
		"door_internal",
		"doors",
		"driveways",
		"electrical_installation",
		"electronics",
		"entertainers",
		"ev_charger",
		"events",
		"experiences",
		"fencing",
		"fireplaces",
		"fitted_furniture",
		"flooring_excluding_carpets",
		"flowers",
		"full_events_package",
		"furniture",
		"garage_doors",
		"garden_buildings",
		"gates",
		"glass_splash_backs",
		"granite_worktops",
		"graphic_designer",
		"ground_source_heat_pumps",
		"high_end_clothing",
		"home_lifts",
		"home_removals",
		"home_study",
		"hot_tubs_and_spas",
		"insulation_roof_foil_wrap_only",
		"jewllery",
		"kitchens_fitted",
		"kitchens_supply_only",
		"landscaping",
		"loft_boarding",
		"loft_conversion",
		"media_walls",
		"medical_assessments",
		"memberships",
		"mobillity_and_mobility_scooters",
		"network_engineer",
		"number_plates",
		"other",
		"painting_and_decorating",
		"patios",
		"personal_security",
		"photography",
		"planners",
		"plastering",
		"porch",
		"rendering",
		"resin_driveways",
		"roofing",
		"roofing_excl_flat_roofs",
		"roofline",
		"security_lighting",
		"solar_pv_panels",
		"sports equipment",
		"stair_lifts",
		"staircases",
		"technology_repair",
		"tiling",
		"tool sales",
		"tyres",
		"under_stair_storage",
		"underfloor_heating",
		"upvc_doors",
		"vehicle_wrapping",
		"venues",
		"verandas",
		"wall_insulation_and_cladding",
		"wardrobes",
		"water_softeners",
		"website_builder",
		"windows",
		"windows_and_doors",
	}
}
