// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package schema

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CompanyCompanyType.
const (
	LimitedCompany CompanyCompanyType = "limited_company"
	SoleTrader     CompanyCompanyType = "sole_trader"
)

// Defines values for CompanyLifecycle.
const (
	CompanyLifecycleCompletedSetup CompanyLifecycle = "completed_setup"
	CompanyLifecycleOnboarded      CompanyLifecycle = "onboarded"
	CompanyLifecycleRegistered     CompanyLifecycle = "registered"
	CompanyLifecycleVerified       CompanyLifecycle = "verified"
)

// Defines values for CompanyQuotePreference.
const (
	Custom       CompanyQuotePreference = "custom"
	Kanda        CompanyQuotePreference = "kanda"
	NoPreference CompanyQuotePreference = "no_preference"
)

// Defines values for CompanySkipDeposit.
const (
	CompanySkipDepositNo  CompanySkipDeposit = "No"
	CompanySkipDepositYes CompanySkipDeposit = "Yes"
)

// Defines values for CompanyInfoTradeBody.
const (
	Elecsa  CompanyInfoTradeBody = "elecsa"
	GasSafe CompanyInfoTradeBody = "gas_safe"
	Napit   CompanyInfoTradeBody = "napit"
	Niceic  CompanyInfoTradeBody = "niceic"
	Other   CompanyInfoTradeBody = "other"
)

// Defines values for CompanyInfoTradeType.
const (
	AirConditioning              CompanyInfoTradeType = "air_conditioning"
	Bathrooms                    CompanyInfoTradeType = "bathrooms"
	CctvAndSecurityInstallations CompanyInfoTradeType = "cctv_and_security_installations"
	DrivewaysAndPatios           CompanyInfoTradeType = "driveways_and_patios"
	Electrician                  CompanyInfoTradeType = "electrician"
	EvChargerInstaller           CompanyInfoTradeType = "ev_charger_installer"
	Fireplaces                   CompanyInfoTradeType = "fireplaces"
	FloorLayer                   CompanyInfoTradeType = "floor_layer"
	GarageDoors                  CompanyInfoTradeType = "garage_doors"
	GasEngineer                  CompanyInfoTradeType = "gas_engineer"
	KitchenFitter                CompanyInfoTradeType = "kitchen_fitter"
	Landscaping                  CompanyInfoTradeType = "landscaping"
	MultiTrade                   CompanyInfoTradeType = "multi_trade"
	OtherTrade                   CompanyInfoTradeType = "other_trade"
	Tiler                        CompanyInfoTradeType = "tiler"
	WindowsAndDoors              CompanyInfoTradeType = "windows_and_doors"
)

// Defines values for CompanyInfoUseSubcontractor.
const (
	CompanyInfoUseSubcontractorNo  CompanyInfoUseSubcontractor = "no"
	CompanyInfoUseSubcontractorYes CompanyInfoUseSubcontractor = "yes"
)

// Defines values for CreditKind.
const (
	CreditKindCharge       CreditKind = "charge"
	CreditKindChargeRefund CreditKind = "charge_refund"
	CreditKindJob          CreditKind = "job"
	CreditKindJobPayout    CreditKind = "job_payout"
	CreditKindJobRefund    CreditKind = "job_refund"
)

// Defines values for CreditProvider.
const (
	CreditProviderDuologi CreditProvider = "duologi"
	CreditProviderOmni    CreditProvider = "omni"
)

// Defines values for CreditState.
const (
	CreditStateAccepted       CreditState = "accepted"
	CreditStateActionCustomer CreditState = "action_customer"
	CreditStateActionLender   CreditState = "action_lender"
	CreditStateDeclined       CreditState = "declined"
	CreditStateFinished       CreditState = "finished"
	CreditStatePaidOut        CreditState = "paid_out"
	CreditStatePending        CreditState = "pending"
	CreditStateReferred       CreditState = "referred"
)

// Defines values for DirectorInfoVerificationStatus.
const (
	DirectorInfoVerificationStatusNotVerified DirectorInfoVerificationStatus = "not_verified"
	DirectorInfoVerificationStatusVerified    DirectorInfoVerificationStatus = "verified"
)

// Defines values for JobDepositType.
const (
	FixedDeposit   JobDepositType = "fixed_deposit"
	NoDeposit      JobDepositType = "no_deposit"
	PartialDeposit JobDepositType = "partial_deposit"
)

// Defines values for JobFinanceStatus.
const (
	JobFinanceStatusAppliedForFinance  JobFinanceStatus = "applied_for_finance"
	JobFinanceStatusFinacneNotApproved JobFinanceStatus = "finacne_not_approved"
	JobFinanceStatusFinanceDepositPaid JobFinanceStatus = "finance_deposit_paid"
	JobFinanceStatusFinanced           JobFinanceStatus = "financed"
	JobFinanceStatusPaid               JobFinanceStatus = "paid"
	JobFinanceStatusSatNoteSent        JobFinanceStatus = "sat_note_sent"
	JobFinanceStatusSatNoteSigned      JobFinanceStatus = "sat_note_signed"
	JobFinanceStatusSatNoteViewed      JobFinanceStatus = "sat_note_viewed"
	JobFinanceStatusUnderReview        JobFinanceStatus = "under_review"
)

// Defines values for JobStatus.
const (
	JobStatusAccepted JobStatus = "accepted"
	JobStatusArchived JobStatus = "archived"
	JobStatusDeclined JobStatus = "declined"
	JobStatusDraft    JobStatus = "draft"
	JobStatusSent     JobStatus = "sent"
)

// Defines values for MoneyCurrency.
const (
	GBP MoneyCurrency = "GBP"
)

// Defines values for PaymentKind.
const (
	PaymentKindCharge       PaymentKind = "charge"
	PaymentKindChargeRefund PaymentKind = "charge_refund"
	PaymentKindJob          PaymentKind = "job"
	PaymentKindJobPayout    PaymentKind = "job_payout"
	PaymentKindJobRefund    PaymentKind = "job_refund"
)

// Defines values for PaymentPaymentMethod.
const (
	Card        PaymentPaymentMethod = "card"
	Cash        PaymentPaymentMethod = "cash"
	DirectDebit PaymentPaymentMethod = "direct_debit"
	Loan        PaymentPaymentMethod = "loan"
)

// Defines values for PaymentProvider.
const (
	PaymentProviderBankTransfer PaymentProvider = "bank_transfer"
	PaymentProviderDuologi      PaymentProvider = "duologi"
	PaymentProviderGocardless   PaymentProvider = "gocardless"
	PaymentProviderOmni         PaymentProvider = "omni"
	PaymentProviderStripe       PaymentProvider = "stripe"
)

// Defines values for PaymentStatus.
const (
	PaymentStatusCancelled PaymentStatus = "cancelled"
	PaymentStatusDisputed  PaymentStatus = "disputed"
	PaymentStatusPaid      PaymentStatus = "paid"
	PaymentStatusPending   PaymentStatus = "pending"
	PaymentStatusRefunded  PaymentStatus = "refunded"
	PaymentStatusUnpaid    PaymentStatus = "unpaid"
)

// Defines values for UserTypeRole.
const (
	CompanyAdmin   UserTypeRole = "company-admin"
	CompanyManager UserTypeRole = "company-manager"
	CompanyStaff   UserTypeRole = "company-staff"
)

// Address defines model for Address.
type Address struct {
	BuildingName   *string `json:"building_name,omitempty"`
	BuildingNumber *string `json:"building_number,omitempty"`
	City           string  `json:"city"`
	Country        string  `json:"country"`
	County         *string `json:"county,omitempty"`
	Line1          string  `json:"line_1"`
	Line2          *string `json:"line_2,omitempty"`
	Postcode       string  `json:"postcode"`
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Audience *string             `json:"audience,omitempty"`
	Disabled *bool               `json:"disabled,omitempty"`
	Email    openapi_types.Email `json:"email"`
	Id       *string             `json:"id,omitempty"`
	Issuer   *string             `json:"issuer,omitempty"`
	Name     string              `json:"name"`
	Phone    *string             `json:"phone,omitempty"`
	PhotoURL *string             `json:"photoURL,omitempty"`
	Provider *string             `json:"provider,omitempty"`
	Role     *string             `json:"role,omitempty"`
	Subject  *string             `json:"subject,omitempty"`
	Token    *string             `json:"token,omitempty"`
}

// AvailableRate defines model for AvailableRate.
type AvailableRate struct {
	Enabled bool   `json:"enabled"`
	Fee     int    `json:"fee"`
	Name    string `json:"name"`
}

// Company defines model for Company.
type Company struct {
	AvailableRates  *[]AvailableRate        `json:"available_rates,omitempty"`
	Cid             *string                 `json:"cid,omitempty"`
	CompanyInfo     *CompanyInfo            `json:"company_info,omitempty"`
	CompanyLogo     *Document               `json:"company_logo,omitempty"`
	CompanyType     CompanyCompanyType      `json:"company_type"`
	CompanyTypeInfo interface{}             `json:"company_type_info"`
	Emails          *[]openapi_types.Email  `json:"emails,omitempty"`
	Id              *string                 `json:"id,omitempty"`
	Lifecycle       *CompanyLifecycle       `json:"lifecycle,omitempty"`
	Metadata        *Metadata               `json:"metadata,omitempty"`
	Oid             *string                 `json:"oid,omitempty"`
	QuotePreference *CompanyQuotePreference `json:"quote_preference,omitempty"`
	SkipDeposit     *CompanySkipDeposit     `json:"skip_deposit,omitempty"`
	Users           *[]UserType             `json:"users,omitempty"`
}

// CompanyCompanyType defines model for Company.CompanyType.
type CompanyCompanyType string

// CompanyLifecycle defines model for Company.Lifecycle.
type CompanyLifecycle string

// CompanyQuotePreference defines model for Company.QuotePreference.
type CompanyQuotePreference string

// CompanySkipDeposit defines model for Company.SkipDeposit.
type CompanySkipDeposit string

// CompanyInfo defines model for CompanyInfo.
type CompanyInfo struct {
	AverageJobValue    int                         `json:"average_job_value"`
	AverageMonthlyJobs int                         `json:"average_monthly_jobs"`
	InsuranceDocument  Document                    `json:"insurance_document"`
	TradeBody          *CompanyInfoTradeBody       `json:"trade_body,omitempty"`
	TradeBodyNumber    *string                     `json:"trade_body_number,omitempty"`
	TradeType          CompanyInfoTradeType        `json:"trade_type"`
	UseSubcontractor   CompanyInfoUseSubcontractor `json:"use_subcontractor"`
	WarrantyLength     int                         `json:"warranty_length"`
}

// CompanyInfoTradeBody defines model for CompanyInfo.TradeBody.
type CompanyInfoTradeBody string

// CompanyInfoTradeType defines model for CompanyInfo.TradeType.
type CompanyInfoTradeType string

// CompanyInfoUseSubcontractor defines model for CompanyInfo.UseSubcontractor.
type CompanyInfoUseSubcontractor string

// Credit defines model for Credit.
type Credit struct {
	Amount   Money          `json:"amount"`
	Cid      *string        `json:"cid,omitempty"`
	Customer Customer       `json:"customer"`
	Id       *string        `json:"id,omitempty"`
	Kid      *string        `json:"kid,omitempty"`
	Kind     *CreditKind    `json:"kind,omitempty"`
	Metadata *Metadata      `json:"metadata,omitempty"`
	Oid      *string        `json:"oid,omitempty"`
	Provider CreditProvider `json:"provider"`
	State    *CreditState   `json:"state,omitempty"`
	Xid      *string        `json:"xid,omitempty"`
	Xref     *string        `json:"xref,omitempty"`
}

// CreditKind defines model for Credit.Kind.
type CreditKind string

// CreditProvider defines model for Credit.Provider.
type CreditProvider string

// CreditState defines model for Credit.State.
type CreditState string

// Customer defines model for Customer.
type Customer struct {
	Address   *Address            `json:"address,omitempty"`
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"first_name"`
	LastName  string              `json:"last_name"`
	Phone     string              `json:"phone"`
}

// DirectorInfo defines model for DirectorInfo.
type DirectorInfo struct {
	HomeAddress        Address                         `json:"home_address"`
	VerificationStatus *DirectorInfoVerificationStatus `json:"verification_status,omitempty"`
}

// DirectorInfoVerificationStatus defines model for DirectorInfo.VerificationStatus.
type DirectorInfoVerificationStatus string

// Document defines model for Document.
type Document struct {
	Cid      *string   `json:"cid,omitempty"`
	Content  string    `json:"content"`
	Id       *string   `json:"id,omitempty"`
	Metadata *Metadata `json:"metadata,omitempty"`
	Mimetype *string   `json:"mimetype,omitempty"`
	Name     string    `json:"name"`
	Oid      *string   `json:"oid,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// InfoCompany defines model for InfoCompany.
type InfoCompany struct {
	Directors      *[]UserType        `json:"directors,omitempty"`
	Id             *string            `json:"id,omitempty"`
	LimitedCompany LimitedCompanyInfo `json:"limited_company"`
	Metadata       *Metadata          `json:"metadata,omitempty"`
}

// InfoMe defines model for InfoMe.
type InfoMe struct {
	Name     *string `json:"name,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	PhotoURL *string `json:"photoURL,omitempty"`
}

// Job defines model for Job.
type Job struct {
	Cid           *string           `json:"cid,omitempty"`
	Customer      Customer          `json:"customer"`
	DepositType   JobDepositType    `json:"deposit_type"`
	DepositValue  Money             `json:"deposit_value"`
	Description   *string           `json:"description,omitempty"`
	FinanceStatus *JobFinanceStatus `json:"finance_status,omitempty"`
	Id            *string           `json:"id,omitempty"`
	JobItems      *[]JobItem        `json:"job_items,omitempty"`
	Metadata      *Metadata         `json:"metadata,omitempty"`
	Notes         *[]string         `json:"notes,omitempty"`
	Oid           *string           `json:"oid,omitempty"`
	Status        *JobStatus        `json:"status,omitempty"`
	Title         string            `json:"title"`
}

// JobDepositType defines model for Job.DepositType.
type JobDepositType string

// JobFinanceStatus defines model for Job.FinanceStatus.
type JobFinanceStatus string

// JobStatus defines model for Job.Status.
type JobStatus string

// JobItem defines model for JobItem.
type JobItem struct {
	Description   *string   `json:"description,omitempty"`
	Price         Money     `json:"price"`
	Quantity      Pence     `json:"quantity"`
	QuoteDocument *Document `json:"quote_document,omitempty"`
	Title         string    `json:"title"`
	Vat           Money     `json:"vat"`
}

// LimitedCompanyInfo defines model for LimitedCompanyInfo.
type LimitedCompanyInfo struct {
	CompanyAddress Address  `json:"company_address"`
	CompanyName    string   `json:"company_name"`
	CompanyNumber  string   `json:"company_number"`
	TradingAddress *Address `json:"trading_address,omitempty"`
	VatNumber      *string  `json:"vat_number,omitempty"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Liveness  *bool      `json:"liveness,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Money defines model for Money.
type Money struct {
	Amount   Pence          `json:"amount"`
	Currency *MoneyCurrency `json:"currency,omitempty"`
}

// MoneyCurrency defines model for Money.Currency.
type MoneyCurrency string

// Payment defines model for Payment.
type Payment struct {
	Amount        Money                 `json:"amount"`
	Cid           *string               `json:"cid,omitempty"`
	Customer      *Customer             `json:"customer,omitempty"`
	Id            *string               `json:"id,omitempty"`
	Kid           *string               `json:"kid,omitempty"`
	Kind          *PaymentKind          `json:"kind,omitempty"`
	Metadata      *Metadata             `json:"metadata,omitempty"`
	Oid           *string               `json:"oid,omitempty"`
	PaymentMethod *PaymentPaymentMethod `json:"payment_method,omitempty"`
	Provider      PaymentProvider       `json:"provider"`
	Status        *PaymentStatus        `json:"status,omitempty"`
	Xid           *string               `json:"xid,omitempty"`
	Xref          *string               `json:"xref,omitempty"`
}

// PaymentKind defines model for Payment.Kind.
type PaymentKind string

// PaymentPaymentMethod defines model for Payment.PaymentMethod.
type PaymentPaymentMethod string

// PaymentProvider defines model for Payment.Provider.
type PaymentProvider string

// PaymentStatus defines model for Payment.Status.
type PaymentStatus string

// Pence defines model for Pence.
type Pence int32

// SoleTraderInfo defines model for SoleTraderInfo.
type SoleTraderInfo struct {
	NationalInsuranceNumber string  `json:"national_insurance_number"`
	TradingAddress          Address `json:"trading_address"`
	TradingName             string  `json:"trading_name"`
}

// UserType defines model for UserType.
type UserType struct {
	DirectorInfo *DirectorInfo       `json:"director_info,omitempty"`
	Email        openapi_types.Email `json:"email"`
	FirstName    string              `json:"first_name"`
	LastName     *string             `json:"last_name,omitempty"`
	Mobile       *string             `json:"mobile,omitempty"`
	Role         UserTypeRole        `json:"role"`
}

// UserTypeRole defines model for UserType.Role.
type UserTypeRole string

// PostCompanyJSONBody defines parameters for PostCompany.
type PostCompanyJSONBody Company

// PutCompanyJSONBody defines parameters for PutCompany.
type PutCompanyJSONBody Company

// PostCreditJSONBody defines parameters for PostCredit.
type PostCreditJSONBody Credit

// PutCreditJSONBody defines parameters for PutCredit.
type PutCreditJSONBody Credit

// PostDocumentJSONBody defines parameters for PostDocument.
type PostDocumentJSONBody Document

// PutDocumentJSONBody defines parameters for PutDocument.
type PutDocumentJSONBody Document

// InfoCompanyParams defines parameters for InfoCompany.
type InfoCompanyParams struct {
	// query keyword of company name
	CompanyName *string `form:"company_name,omitempty" json:"company_name,omitempty"`

	// exact company number match
	CompanyNumber *string `form:"company_number,omitempty" json:"company_number,omitempty"`

	// include directors info?
	Directors *bool `form:"directors,omitempty" json:"directors,omitempty"`
}

// InfoCustomerParams defines parameters for InfoCustomer.
type InfoCustomerParams struct {
	// query keyword of loosely matched customer
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// PostJobJSONBody defines parameters for PostJob.
type PostJobJSONBody Job

// PutJobJSONBody defines parameters for PutJob.
type PutJobJSONBody Job

// PutMeJSONBody defines parameters for PutMe.
type PutMeJSONBody InfoMe

// PostPaymentJSONBody defines parameters for PostPayment.
type PostPaymentJSONBody Payment

// PutPaymentJSONBody defines parameters for PutPayment.
type PutPaymentJSONBody Payment

// PostCompanyJSONRequestBody defines body for PostCompany for application/json ContentType.
type PostCompanyJSONRequestBody PostCompanyJSONBody

// PutCompanyJSONRequestBody defines body for PutCompany for application/json ContentType.
type PutCompanyJSONRequestBody PutCompanyJSONBody

// PostCreditJSONRequestBody defines body for PostCredit for application/json ContentType.
type PostCreditJSONRequestBody PostCreditJSONBody

// PutCreditJSONRequestBody defines body for PutCredit for application/json ContentType.
type PutCreditJSONRequestBody PutCreditJSONBody

// PostDocumentJSONRequestBody defines body for PostDocument for application/json ContentType.
type PostDocumentJSONRequestBody PostDocumentJSONBody

// PutDocumentJSONRequestBody defines body for PutDocument for application/json ContentType.
type PutDocumentJSONRequestBody PutDocumentJSONBody

// PostJobJSONRequestBody defines body for PostJob for application/json ContentType.
type PostJobJSONRequestBody PostJobJSONBody

// PutJobJSONRequestBody defines body for PutJob for application/json ContentType.
type PutJobJSONRequestBody PutJobJSONBody

// PutMeJSONRequestBody defines body for PutMe for application/json ContentType.
type PutMeJSONRequestBody PutMeJSONBody

// PostPaymentJSONRequestBody defines body for PostPayment for application/json ContentType.
type PostPaymentJSONRequestBody PostPaymentJSONBody

// PutPaymentJSONRequestBody defines body for PutPayment for application/json ContentType.
type PutPaymentJSONRequestBody PutPaymentJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// get all companies
	// (GET /api/company)
	GetCompanies(ctx echo.Context) error
	// post new company
	// (POST /api/company)
	PostCompany(ctx echo.Context) error
	// delete existing company
	// (DELETE /api/company/{id})
	DeleteCompany(ctx echo.Context, id string) error
	// get existing company
	// (GET /api/company/{id})
	GetCompany(ctx echo.Context, id string) error
	// put existing company
	// (PUT /api/company/{id})
	PutCompany(ctx echo.Context, id string) error
	// get all credits
	// (GET /api/credit)
	GetCredits(ctx echo.Context) error
	// post new credit
	// (POST /api/credit)
	PostCredit(ctx echo.Context) error
	// delete existing credit
	// (DELETE /api/credit/{id})
	DeleteCredit(ctx echo.Context, id string) error
	// get existing credit
	// (GET /api/credit/{id})
	GetCredit(ctx echo.Context, id string) error
	// put existing credit
	// (PUT /api/credit/{id})
	PutCredit(ctx echo.Context, id string) error
	// get all documents
	// (GET /api/document)
	GetDocuments(ctx echo.Context) error
	// post new document
	// (POST /api/document)
	PostDocument(ctx echo.Context) error
	// delete existing document
	// (DELETE /api/document/{id})
	DeleteDocument(ctx echo.Context, id string) error
	// get existing document
	// (GET /api/document/{id})
	GetDocument(ctx echo.Context, id string) error
	// put existing document
	// (PUT /api/document/{id})
	PutDocument(ctx echo.Context, id string) error
	// query company info with its directors
	// (GET /api/info/company)
	InfoCompany(ctx echo.Context, params InfoCompanyParams) error
	// query customer info with loose query
	// (GET /api/info/customer)
	InfoCustomer(ctx echo.Context, params InfoCustomerParams) error
	// get all jobs
	// (GET /api/job)
	GetJobs(ctx echo.Context) error
	// post new job
	// (POST /api/job)
	PostJob(ctx echo.Context) error
	// delete existing job
	// (DELETE /api/job/{id})
	DeleteJob(ctx echo.Context, id string) error
	// get existing job
	// (GET /api/job/{id})
	GetJob(ctx echo.Context, id string) error
	// put existing job
	// (PUT /api/job/{id})
	PutJob(ctx echo.Context, id string) error
	// get me info
	// (GET /api/me)
	Me(ctx echo.Context) error
	// put me info
	// (PUT /api/me)
	PutMe(ctx echo.Context) error
	// get all payments
	// (GET /api/payment)
	GetPayments(ctx echo.Context) error
	// post new payment
	// (POST /api/payment)
	PostPayment(ctx echo.Context) error
	// delete existing payment
	// (DELETE /api/payment/{id})
	DeletePayment(ctx echo.Context, id string) error
	// get existing payment
	// (GET /api/payment/{id})
	GetPayment(ctx echo.Context, id string) error
	// put existing payment
	// (PUT /api/payment/{id})
	PutPayment(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetCompanies converts echo context to params.
func (w *ServerInterfaceWrapper) GetCompanies(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCompanies(ctx)
	return err
}

// PostCompany converts echo context to params.
func (w *ServerInterfaceWrapper) PostCompany(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostCompany(ctx)
	return err
}

// DeleteCompany converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCompany(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteCompany(ctx, id)
	return err
}

// GetCompany converts echo context to params.
func (w *ServerInterfaceWrapper) GetCompany(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCompany(ctx, id)
	return err
}

// PutCompany converts echo context to params.
func (w *ServerInterfaceWrapper) PutCompany(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutCompany(ctx, id)
	return err
}

// GetCredits converts echo context to params.
func (w *ServerInterfaceWrapper) GetCredits(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCredits(ctx)
	return err
}

// PostCredit converts echo context to params.
func (w *ServerInterfaceWrapper) PostCredit(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostCredit(ctx)
	return err
}

// DeleteCredit converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCredit(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteCredit(ctx, id)
	return err
}

// GetCredit converts echo context to params.
func (w *ServerInterfaceWrapper) GetCredit(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCredit(ctx, id)
	return err
}

// PutCredit converts echo context to params.
func (w *ServerInterfaceWrapper) PutCredit(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutCredit(ctx, id)
	return err
}

// GetDocuments converts echo context to params.
func (w *ServerInterfaceWrapper) GetDocuments(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetDocuments(ctx)
	return err
}

// PostDocument converts echo context to params.
func (w *ServerInterfaceWrapper) PostDocument(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostDocument(ctx)
	return err
}

// DeleteDocument converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDocument(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteDocument(ctx, id)
	return err
}

// GetDocument converts echo context to params.
func (w *ServerInterfaceWrapper) GetDocument(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetDocument(ctx, id)
	return err
}

// PutDocument converts echo context to params.
func (w *ServerInterfaceWrapper) PutDocument(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutDocument(ctx, id)
	return err
}

// InfoCompany converts echo context to params.
func (w *ServerInterfaceWrapper) InfoCompany(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params InfoCompanyParams
	// ------------- Optional query parameter "company_name" -------------

	err = runtime.BindQueryParameter("form", true, false, "company_name", ctx.QueryParams(), &params.CompanyName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter company_name: %s", err))
	}

	// ------------- Optional query parameter "company_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "company_number", ctx.QueryParams(), &params.CompanyNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter company_number: %s", err))
	}

	// ------------- Optional query parameter "directors" -------------

	err = runtime.BindQueryParameter("form", true, false, "directors", ctx.QueryParams(), &params.Directors)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter directors: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InfoCompany(ctx, params)
	return err
}

// InfoCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) InfoCustomer(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params InfoCustomerParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InfoCustomer(ctx, params)
	return err
}

// GetJobs converts echo context to params.
func (w *ServerInterfaceWrapper) GetJobs(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetJobs(ctx)
	return err
}

// PostJob converts echo context to params.
func (w *ServerInterfaceWrapper) PostJob(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostJob(ctx)
	return err
}

// DeleteJob converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteJob(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteJob(ctx, id)
	return err
}

// GetJob converts echo context to params.
func (w *ServerInterfaceWrapper) GetJob(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetJob(ctx, id)
	return err
}

// PutJob converts echo context to params.
func (w *ServerInterfaceWrapper) PutJob(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutJob(ctx, id)
	return err
}

// Me converts echo context to params.
func (w *ServerInterfaceWrapper) Me(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Me(ctx)
	return err
}

// PutMe converts echo context to params.
func (w *ServerInterfaceWrapper) PutMe(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutMe(ctx)
	return err
}

// GetPayments converts echo context to params.
func (w *ServerInterfaceWrapper) GetPayments(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPayments(ctx)
	return err
}

// PostPayment converts echo context to params.
func (w *ServerInterfaceWrapper) PostPayment(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostPayment(ctx)
	return err
}

// DeletePayment converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePayment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeletePayment(ctx, id)
	return err
}

// GetPayment converts echo context to params.
func (w *ServerInterfaceWrapper) GetPayment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPayment(ctx, id)
	return err
}

// PutPayment converts echo context to params.
func (w *ServerInterfaceWrapper) PutPayment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutPayment(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/company", wrapper.GetCompanies)
	router.POST(baseURL+"/api/company", wrapper.PostCompany)
	router.DELETE(baseURL+"/api/company/:id", wrapper.DeleteCompany)
	router.GET(baseURL+"/api/company/:id", wrapper.GetCompany)
	router.PUT(baseURL+"/api/company/:id", wrapper.PutCompany)
	router.GET(baseURL+"/api/credit", wrapper.GetCredits)
	router.POST(baseURL+"/api/credit", wrapper.PostCredit)
	router.DELETE(baseURL+"/api/credit/:id", wrapper.DeleteCredit)
	router.GET(baseURL+"/api/credit/:id", wrapper.GetCredit)
	router.PUT(baseURL+"/api/credit/:id", wrapper.PutCredit)
	router.GET(baseURL+"/api/document", wrapper.GetDocuments)
	router.POST(baseURL+"/api/document", wrapper.PostDocument)
	router.DELETE(baseURL+"/api/document/:id", wrapper.DeleteDocument)
	router.GET(baseURL+"/api/document/:id", wrapper.GetDocument)
	router.PUT(baseURL+"/api/document/:id", wrapper.PutDocument)
	router.GET(baseURL+"/api/info/company", wrapper.InfoCompany)
	router.GET(baseURL+"/api/info/customer", wrapper.InfoCustomer)
	router.GET(baseURL+"/api/job", wrapper.GetJobs)
	router.POST(baseURL+"/api/job", wrapper.PostJob)
	router.DELETE(baseURL+"/api/job/:id", wrapper.DeleteJob)
	router.GET(baseURL+"/api/job/:id", wrapper.GetJob)
	router.PUT(baseURL+"/api/job/:id", wrapper.PutJob)
	router.GET(baseURL+"/api/me", wrapper.Me)
	router.PUT(baseURL+"/api/me", wrapper.PutMe)
	router.GET(baseURL+"/api/payment", wrapper.GetPayments)
	router.POST(baseURL+"/api/payment", wrapper.PostPayment)
	router.DELETE(baseURL+"/api/payment/:id", wrapper.DeletePayment)
	router.GET(baseURL+"/api/payment/:id", wrapper.GetPayment)
	router.PUT(baseURL+"/api/payment/:id", wrapper.PutPayment)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdXXPcNnf+Kxg2F+3MriU7nU66Nx4naVO7ceKxk4tUo3Kw5NldSCRAg+BKG7/67+/g",
	"iwRIEKRkW6HHubF3yQPg4Hw+5xBcfUgyVlaMAhV1svmQ1NkBSqw+vshzDrX6WHFWARcE1LdtQ4qc0H1K",
	"cQnyQknoz0D34pBsnq4SQUQByaYlQ4pslYhTJS/XghO6T+5WzjxNuQU+ZyZNGJgrI+I0PoG8i86QYDc0",
	"OJg1VPDYeEMwNnZqqFy8FlgExVAQCunT8RnkffR0dOSziZHPQiMrVouM5Up7FRYCOE02yf//68WL9f/h",
	"9Z+XFy/W/4PXh1frP67Wp8vnF+fr/7w09+TH58i7dPnh2d0/Ln7aX168JJcXb/klen5+8QLLy//2TdLx",
	"Y1dFZ+hPUqn1+7ytktv1NaY5Xu8YL9c3JN+DSDbJG8vw3d0q4fC+IRzyZHNhpWcsYOWoqt3jZbsI215B",
	"JqQAXjTi8Hutjc63btzkBGimRMMB57/S4pRsBG+g20hLExBtTmq8LSRz4+Nbmnb8lrECMJUTQIlJIUdL",
	"CWC5eX2lG95+769NoquSPDimrhsth9FxmiIwNh4Axvy+OjAaGaZvh8cJ9vvbnz3ZNJwk3ljBkKQJjefs",
	"SPL4XluawHjOiqhVqPuBcXWjzS4y1JIERgt2DTQ2VhMMRvb8RCvfkBrNWDtyNt0x4ti4MYCgHx0xKaQt",
	"v5XRbeBMQFtfaI1XX3oetP0dWMMgZVMmm/Num/JWO4RQAXvgD7XBnmwMkV7Bshza7Q+srDA9BYKGFUPK",
	"sdCXiIBSffiGwy7ZJP9y1mXaM5Nmz3zx3TkRxt5AesKWGcw5PumMF3X2TLOKwk5v7qaE7tgUj2bTLyWp",
	"M7Rg+8mhP7KsKYEKd5zmRZqGVLAM4CURkKfmvrRBVkAqOM6NzfV2pCaYmzfe4pywd1AYBbpMtJtnFH7d",
	"JZuL+F5+1nz60ogPeccK+E3tQ5OPbAYpRgLmpvzTN6ZhThhEqRGD0JOhHeOoqYGjmwNDB1wjXBGEs0wi",
	"vaGRzbOxhpL3DYyYWkF2kJ0yHTpz2OGmkPxz2JNaAFdJ0NqCd5HRLcM8V5/lSgVIM6lBNFWySo7AyY5o",
	"P53ir2VhHISVIHCOBZ6y6NeW7m6VsLh02A0FPiKU9w0TkFYcdsAt2OhkQ5l7qxNP/7oyeCmdphasdH1F",
	"zY884mFauiZVmkPFaiL89X9hzqJ/qOjzCwu5IqkRLgp2AzkSDAl8DYjdUGQnDSwqTW9+eJQI7Tc5hRMZ",
	"9Qx9U+1FdC/YhNw+Et1fmrDQj/DA8R7SK7ZNj7ho/Dz11I3cihBdsS3ShKGsZacrGRWH4iSnradmNLRI",
	"0YYmJbRuOKYZpLkNvPcI0CripluWn9zwTEkGJJP2UEBWS2vb4zqt8Q4UjqiUmpk4+LFazYXUXHMjdRek",
	"O0YmK8NunUhtqOfr5x25DaB7QkGNUqtzkhEsARIc0+yA+R54SmgtcFHoqYn+/5qI7AA03RFZOknoUDDG",
	"0wKf1LcsE8cUUxmssoYTcbKTYEEYlbq7ITRnN7UiyhlTBl1gmtcZrrSQMOFpxmhO5BB9aYvFgTNWSuKc",
	"kyPc4JOeopIT10o3yqrslDvCoSpwply4bApBdF61KjPfBoq7V4rtFNfUkNbNNmNUcJwJxl15nxQT1Isj",
	"TQ3IG/D8AaveyBBAxSktjH2EvciSIUM2dKBeDHHMZrjIiAevAnEiJJegrwZjEodch+deOCplnTuZrRiF",
	"TwAWVXrRbhgFipZuEjhU+CR3PLLe9UQZSwVwigt0TWg+OgXNXeO7YttkJf9NK3xijTBfOOwaqvCFcvb2",
	"g70RwRYeFwtAFG5xa3fNSiqL47xhBdsTx77uB5o1aHLmlXCxEgqY5ZAVhKqPCmxo6IYzGbWkr+iq0nxv",
	"DWmVVEBzzcKOUFIf1LAKkzyV2nGhhnKAceB2GxcZ3Bo1tVBoRH63SkX3mWiyrHS321XYxnODzu44Ws/d",
	"u15stJw0ZB/XRdoRXouJ5q6iGe3sFnhyAkmCPqZDNJrwe1pwduMy5nQ/1GIhffxIOMhwHUaEB1ZCen/F",
	"6MIlU1AglWbd1B7eYiJta5t5ZY47IzIzTknFYz64dwdB+vv+yMYDFWbW1jC3uIb/+HfHMm1GRJZ6buD6",
	"b1LAdPZppyefLHCXpAQLMCeXlcRhiDXZzmrnGPOcB2eQcEvMKiBkIf/FOQuEKvtYoVUvoeLbZ0msSs/D",
	"NVIJdY33UZlakqntWLrQPqR3jzb2chMCHlazjvf/zay91s89+y5y8FTzxW+ubR7Q43qAQwye0fhcjGnh",
	"daCD/CU9YrgL7OsV237qEPoAOG46Mm0R7PWaunaN02jqLlaYC4IL58qO3ELefnfAmrk0GtwsG20DZVbx",
	"kkOdcVLJ9Dau0iu2RS5hENdQVXANk24jcWrK4UjgRkK0qioI5OmO8dQMSrrhdhMSrZrLGYVUJm5cSaAH",
	"eUctP9ZYyLuQ1jqXtd/lcj0KsqctFI7lfDP9aLqfCiFSXGHzknVRG+hmRbxXbPtSQOk26dT0auwwtj0k",
	"v0rh+AwNuzzO0pp8uPRH1FdDo8k53il1aq2GiyLMswM5xvGb5Hhcj4YqZvf681QOtFReLOj7pBNeLsPR",
	"TKl6mCfn+qhU4JSjVpxk88PD+wZTYY5/xAa8UUVb23x/UIt0WhdqfyMKWSVHPLdnM6K8drNWSnrOkK4C",
	"yTwA1nRj/P5ljB0Zz882kwXz9BiKt2DMXWWiD9yuE20CE7p/SMEmg/PE+kcs5tajnuBWAw0M9hxS7Wsn",
	"hPYUygFLqIX9EivHAtaCqBVHUYceirAII8kjUCO4sRlamtCj/abKH8qZGRrkbAA1WxYcUXirBwWqnO6B",
	"XdY2sGQN50Czk4+wfvr+jQOt5De3vWWHTG0s0jZ6o7upfzeJ/24STzWJtUjTEsSBeXsvmHrulWGuAIyq",
	"T9MctgrvZ7g+uEZrNWOmeWBbeUbHeqWmVDBlzyRvhXbtLabXqeCY1jsvQs5+ZhQqAQye7zrT5kJO6qrR",
	"wC6TmLsobLtblg1R/VtBjaO7Bbev5/Ws39jjC4N+T+gQl54InZlkiQhFlc+M0//pHZ8JtAYkgMRF2j1L",
	"m8rTdghqh3wWyGBHxsGRoUIzz6iNbba33JDvkNraLtVox2vW2TCvQ/6lP3Uo2ZbE4L25HzkZaoOJSZVr",
	"nJeEdpBuXWKK9/qIgLlSC7zbhY7WBA+TzoqsPcMxE3mPQbQShnYhI6M5svBOalhbxPeAOfAXjX62rlSv",
	"sJ263PF4EKJK7u7UORRtOV5RmPyvZBy9A34kGaAXb14itQZ2jMMnWSui2hIdgdd6pqdPzp+cq1RYAcUV",
	"STbJt+qSjNnioJg+wxU5c9qeSlAf5AiuPOllLqEZCF1sENUu4FBXjNZ618/Oz3WF1D6wUG0h/Zjl7KrW",
	"ha7hbm6rxClteueX+n2uZM8EwkWBspZBRWJQ5T0Yi/Gje/iB1RsKtxVkEnWDoVkldVOWmJ8kc9BnbpUI",
	"vK+lwdk9Xpr3DIZif8Nq8UN73FMaK9Tie3Pw6JPsq5XzcGeSJUThBmUeB9pdZNK8+0hD+Ai+IPc4W5DC",
	"A1Ib6vtu5bnd2QeS3+k4UIA+QeDbwY/qemcJFea4BKFOCF70w4dXfhAlMawO4uiIrw+4+5pcOULphfRe",
	"rr38a3SuBZMjuCW1kFBggZrXPA5ZDDt8PMx+lUqWgXzJCpaxfKZ2qyYUzZvlaPdxM0kTFNwyskmzbKMb",
	"kV0kp7QHIUdDjKJ4JBynubkPjDPcLRHEtYJrxa+3N4HgNNFncjsj4Bh+c9d/JIeLcmXRW2sbywNvVmQD",
	"RftuNhe52eniUV+f4PzyUvqosoewbXEqH6C2Uc2vJgLq16deH7AtTrU+XovodRStLUOvj5o0mpDMFpE4",
	"mkUbW1hwo+nDPVQxFlbsgYrHQWre8Y2ZWC1vOVwgWssd8Vk9tJuMI7aW7PO4XyfqCGrLfR4ex/2mODPI",
	"LXdsZXHYzRFcQO19B5yJ4ByLiCYD/8j8l5TmY6of4LglGkAfycXtYDUZdr9OVXuYbolq9lDdlI7HkN2C",
	"dPzI6aUJS28hKaZZuPGNiS+SaAjdscnnq+6rNRMm+b4BfkLXcLphPEdsh3pHR0lL1Flp7yhlJ6PBUYr+",
	"anCLM4H8U6OoxCI7TC1lz1zcYzFCs6LJAflv/TwfWal74yiwSHue8qMD6Szw7OpvJn52301akolr+/Le",
	"nLoh4oCIqJErcmvy7tb7Vu8cdRw3e+fl33vZfcFYDcVJWyPkyHmLOGQu76O2+ChW4h7pnGUihn6pNuKy",
	"p41E6QRZyXsm0r4t0drIlX7jawyHvdK/E/H51fKKbe9T9Krfr1hgvWt/7cYIXe4qXuW+Usd4PwcCURKN",
	"1LZX7cqPgzki/JiK9krbwOKKWS0pX6eO/8ysXrWmo+G1fc/tSypkRvQ6KFcXpt1+pRpS8ioWF78mZXoF",
	"6cIU6dWiYS2OVaB/uRYfL+o3AyH99ZG/Wa5RBeQVjv/6/HYwTLyG5DMKtf1N6BF3LWFxiFV6atn9gKiR",
	"Z7uRmKcaWX56fzG/5DBinoZblINQP276mF4TU7DD29K8Jqpg6zVV9xLgWIY17wk+TvVhX0q8RwVSWf4W",
	"WIVUneysEuwO49WIpfo8vtZKOVKVVB4Hj+NpE3yZ6qTqbGRxFUontaG+ez43s1rpLCEKj7zXXr8koBvR",
	"+aByWaDm+9VLzABWUzH2a1SyV9EsUMFeVRPX7hhmWox2HzeTNEHBLSObNMs2uhHZBXKK8+6lMin3rcuL",
	"S6n2GvjRGlzDC/PKZb05Ozs02yfqvdAnGXvSXKs/TDCgWL/HEaLN2VnBMlwcWC02351/d57cXd79MwAA",
	"//+lY18gHmoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
