openapi: "3.0.0"
info:
  version: 1.0.0
  title: Kanda Service - API schema
  description: Kanda Service API Schema

servers:
  # NOTE: replace with correct server url at build time
  - url: https://SCHEMA_URL

paths:
  /api/onboarding:
    post:
      operationId: createOnboarding
      summary: Create new Onboarding
      tags:
        - Company
      requestBody:
        description: onboarding company object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Company"
      responses:
        200:
          description: Created onboarding company object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/me:
    get:
      operationId: me
      summary: Get Me info
      tags:
        - AuthUser
      responses:
        200:
          description: Me info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthUser"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    AuthUser:
      type: object
      properties:
        uid:
          type: string
        token:
          type: string
        name:
          type: string
        email:
          type: string
        role:
          type: string
        phone:
          type: string
        photoURL:
          type: string
        disabled:
          type: boolean
        provider:
          type: string
        subject:
          type: string
        audience:
          type: string
        issuer:
          type: string

    Metadata:
      type: object
      properties:
        liveness:
          type: boolean
          title: liveness
        created_at:
          type: string
          format: date-time
          title: created at
        updated_at:
          type: string
          format: date-time
          title: updated at

    Address:
      type: object
      required:
        - line_1
        - city
        - country
        - postcode
      properties:
        building_number:
          type: string
          title: building number
        building_name:
          type: string
          title: building name
        line_1:
          type: string
          title: line 1
        line_2:
          type: string
          title: line 2
        city:
          type: string
          title: city / town
        county:
          type: string
          title: county / state
        country:
          type: string
          title: country
        postcode:
          type: string
          title: postcode / zipcode

    Company:
      type: object
      required:
        - company_info
        - company_type
        - company_type_info
      properties:
        company_info:
          type: object
          $ref: "#/components/schemas/CompanyInfo"
          title: company info
        users:
          type: array
          items:
            $ref: "#/components/schemas/UserType"
          title: users
        company_type:
          type: string
          enum:
            - limited_company
            - sole_trader
          title: company type
        company_type_info:
          type: object
          oneOf:
            - $ref: "#/components/schemas/LimitedCompanyInfo"
            - $ref: "#/components/schemas/SoleTraderInfo"
          title: company type info
        available_rates:
          type: array
          items:
            $ref: "#/components/schemas/AvailableRate"
          title: available rates
        metadata:
          type: object
          $ref: "#/components/schemas/Metadata"
          title: metadata

    CompanyInfo:
      type: object
      required:
        - trade_type
        - warranty_length
        - average_monthly_jobs
        - average_job_value
        - use_subcontractor
        - insurance_document
      properties:
        trade_type:
          type: string
          enum:
            - gas_engineer
            - electrician
            - ev_charger_installer
            - tiler
            - kitchen_fitter
            - floor_layer
            - cctv_and_security_installations
            - windows_and_doors
            - landscaping
            - air_conditioning
            - bathrooms
            - driveways_and_patios
            - garage_doors
            - fireplaces
            - multi_trade
            - other_trade
          title: trade type
        trade_body:
          type: string
          enum:
            - niceic
            - elecsa
            - gas_safe
            - napit
            - other
          title: trade body
        trade_body_number:
          type: string
          title: trade body number
        warranty_length:
          type: integer
          title: warranty length
        average_monthly_jobs:
          type: integer
          title: average monthly jobs
        average_job_value:
          type: integer
          title: average job value
        use_subcontractor:
          type: boolean
          title: use subcontractor?
        insurance_document:
          type: string
          format: base64
          title: insurance document

    LimitedCompanyInfo:
      type: object
      required:
        - company_name
        - company_address
        - trading_address
      properties:
        company_name:
          type: string
          title: company name
        company_address:
          type: object
          $ref: "#/components/schemas/Address"
          title: company address
        trading_address:
          type: object
          $ref: "#/components/schemas/Address"
          title: trading address

    SoleTraderInfo:
      type: object
      required:
        - national_insurance_number
        - trading_name
        - trading_address
      properties:
        national_insurance_number:
          type: string
          title: national insurance number
        trading_name:
          type: string
          title: trading name
        trading_address:
          type: object
          $ref: "#/components/schemas/Address"
          title: trading address

    DirectorInfo:
      type: object
      required:
        - verification_status
        - home_address
      properties:
        verification_status:
          type: string
          enum:
            - not_verified
            - verified
          title: verification status
        home_address:
          type: object
          $ref: "#/components/schemas/Address"
          title: home address

    UserType:
      type: object
      required:
        - role
        - first_name
        - email
        - mobile
      properties:
        director_info:
          type: object
          $ref: "#/components/schemas/DirectorInfo"
          title: director info
        role:
          type: string
          enum:
            - company-admin
            - company-manager
            - company-staff
          title: company role
        first_name:
          type: string
          title: first name
        last_name:
          type: string
          title: last name
        email:
          type: string
          format: email
          title: email
        mobile:
          type: string
          title: mobile

    AvailableRate:
      type: object
      required:
        - name
        - fee
        - enabled
      properties:
        name:
          type: string
          title: name
        fee:
          type: integer
          title: fee
        enabled:
          type: boolean
          title: enabled?

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          title: code
        message:
          type: string
          title: message

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
