import { FunctionComponent } from 'react';
import * as TE from 'fp-ts/lib/TaskEither';
import type { GuardFunctionRouteProps, GuardToRoute, Next } from 'react-router-guards/dist/types';
import type { ToolkitStore } from '@reduxjs/toolkit/dist/configureStore';
import type { PathKey } from '../store/types';
import type { PageList } from './types';
import { WrapperProps } from './Page';
import { CreatePageArgs } from './helpers';
import type { StringIndexedObject } from '../types';
import type { RoutedApp } from './types';
import { AuthUser, InfoGhost } from '../generated/components/schemas';
export declare function getInitialDataPathKeyLayout<P extends StringIndexedObject>(pathKey: PathKey<P>): FunctionComponent;
export declare function pathKeyToLoadingDependencies<State, P extends StringIndexedObject>(pathKey: PathKey<P>): Readonly<(keyof State)[]>;
export declare function getPageUrls<P extends StringIndexedObject>(pages: PageList<P>): Record<keyof P, string>;
export declare function fetchPageInitialData<State, P extends StringIndexedObject>(store: ToolkitStore<State>, pages: PageList<P>, { page, id }: PathKey<P>, forceReload?: boolean): void;
export declare function initialDataProvider<State, P extends StringIndexedObject>(store: ToolkitStore<State>, pages: PageList<P>, pathKey: PathKey<P>): PathKey<P>;
export declare function getUser(): Promise<AuthUser>;
export declare function ghostUser(email: string): Promise<InfoGhost>;
export declare function isAuthed<P extends StringIndexedObject>(pathKey: PathKey<P>, store: ToolkitStore): () => Promise<TE.TaskEither<Error, PathKey<P>>>;
export declare function createMiddleware<State, P extends StringIndexedObject>(store: ToolkitStore<State>, pages: PageList<P>, unauthorizedRedirectRoute?: string): (to: GuardToRoute, from: GuardFunctionRouteProps | null, next: Next) => void;
export declare function createRoutedApp<State, Keys extends string | number, ExtraState = {}>(store: ToolkitStore<State & ExtraState>, args: Record<Keys, CreatePageArgs<State>>, notFoundPage?: FunctionComponent, Wrapper?: FunctionComponent<WrapperProps>, unauthorizedRedirectRoute?: string): RoutedApp<Keys>;
