import { useDispatch } from 'react-redux';
import type { ThunkDispatch } from '@reduxjs/toolkit';
import type { AuthSlice, createSelectors } from '../store';
import { AuthState } from '../store/slices/auth';
export interface CurrentUserHook {
    user?: AuthState['user'];
    firebaseUser?: AuthState['firebaseUser'];
    isUserLoggedIn: boolean;
    revalidate: () => Promise<unknown>;
    logout: () => void;
}
export declare const createCurrentUserHook: <State extends AuthSlice, Dispatch extends ThunkDispatch<State, unknown, any>, Pages>(dispatch: Dispatch, selectors: {
    getAuth: (state: State) => AuthState;
    getUser: (state: State) => import("..").AuthUser;
    getFirebaseUser: (state: State) => import("@firebase/auth").User;
    getAuthIsLoading: (state: State) => boolean;
    getIsUserLoggedIn: (state: State) => boolean;
    getRoot: (state: State) => State;
    getApp: (state: State) => State["app"];
    getPathKey: (state: State) => import("..").PathKey<Pages>;
    getIsLoading: (state: State) => boolean;
    audit: import("../store/types").Selectors<import("..").Audit, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Audit>>>;
    authUser: import("../store/types").Selectors<import("..").AuthUser, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").AuthUser>>>;
    company: import("../store/types").Selectors<import("..").Company, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Company>>>;
    credit: import("../store/types").Selectors<import("..").Credit, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Credit>>>;
    document: import("../store/types").Selectors<import("..").Document, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Document>>>;
    enterprise: import("../store/types").Selectors<import("..").Enterprise, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Enterprise>>>;
    event: import("../store/types").Selectors<import("..").Event, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Event>>>;
    infoAuth: import("../store/types").Selectors<import("..").InfoAuth, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoAuth>>>;
    infoCompany: import("../store/types").Selectors<import("..").InfoCompany, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoCompany>>>;
    infoEntity: import("../store/types").Selectors<import("..").InfoEntity, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoEntity>>>;
    infoGhost: import("../store/types").Selectors<import("..").InfoGhost, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoGhost>>>;
    infoIP: import("../store/types").Selectors<import("..").InfoIP, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoIP>>>;
    infoLead: import("../store/types").Selectors<import("..").InfoLead, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoLead>>>;
    infoOnboarding: import("../store/types").Selectors<import("..").InfoOnboarding, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoOnboarding>>>;
    infoQuery: import("../store/types").Selectors<import("..").InfoQuery, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoQuery>>>;
    infoRelation: import("../store/types").Selectors<import("..").InfoRelation, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoRelation>>>;
    infoSearch: import("../store/types").Selectors<import("..").InfoSearch, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoSearch>>>;
    infoStats: import("../store/types").Selectors<import("..").InfoStats, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoStats>>>;
    introduction: import("../store/types").Selectors<import("..").Introduction, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Introduction>>>;
    job: import("../store/types").Selectors<import("..").Job, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Job>>>;
    lead: import("../store/types").Selectors<import("..").Lead, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Lead>>>;
    monitor: import("../store/types").Selectors<import("..").Monitor, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Monitor>>>;
    onboarding: import("../store/types").Selectors<import("..").Onboarding, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Onboarding>>>;
    partner: import("../store/types").Selectors<import("..").Partner, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Partner>>>;
    payment: import("../store/types").Selectors<import("..").Payment, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Payment>>>;
    rate: import("../store/types").Selectors<import("..").Rate, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Rate>>>;
    subscription: import("../store/types").Selectors<import("..").Subscription, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Subscription>>>;
    tradeSummary: import("../store/types").Selectors<import("..").TradeSummary, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").TradeSummary>>>;
    training: import("../store/types").Selectors<import("..").Training, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Training>>>;
    transaction: import("../store/types").Selectors<import("..").Transaction, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Transaction>>>;
    postCompanyBilling: import("../store/types").Selectors<import("..").RedirectURLs, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").RedirectURLs>>>;
    getCompanyDirectorVerification: import("../store/types").Selectors<import("..").InfoCompany, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoCompany>>>;
    postCompanyDirectorVerification: import("../store/types").Selectors<import("..").InfoCompany, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoCompany>>>;
    getCompanyReferrals: import("../store/types").Selectors<import("..").Referral, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Referral>>>;
    postCompanyReferrals: import("../store/types").Selectors<import("..").Referral, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Referral>>>;
    exportFcaApproved: import("../store/types").Selectors<import("..").ExportCSV, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").ExportCSV>>>;
    importFcaApproved: import("../store/types").Selectors<import("..").ExportCSV, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").ExportCSV>>>;
    exportEnterpriseDailyReport: import("../store/types").Selectors<import("..").ExportCSV, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").ExportCSV>>>;
    infoSession: import("../store/types").Selectors<import("..").InfoSession, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoSession>>>;
    infoGetCache: import("../store/types").Selectors<import("..").Cache, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Cache>>>;
    infoPutCache: import("../store/types").Selectors<import("..").Cache, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Cache>>>;
    infoDeleteCache: import("../store/types").Selectors<import("..").Cache, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Cache>>>;
    infoCustomer: import("../store/types").Selectors<import("..").Customer, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Customer>>>;
    infoDirector: import("../store/types").Selectors<import("..").OwnerReport, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").OwnerReport>>>;
    infoEnterpriseRole: import("../store/types").Selectors<import("..").EnterpriseUserRole, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").EnterpriseUserRole>>>;
    infoEnterprise: import("../store/types").Selectors<import("..").Enterprise, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Enterprise>>>;
    infoHealth: import("../store/types").Selectors<import("..").Error, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Error>>>;
    infoPartnerBranding: import("../store/types").Selectors<import("..").InfoPartnerBranding, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoPartnerBranding>>>;
    infoLegacyRedirect: import("../store/types").Selectors<import("..").InfoLegacyRedirect, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoLegacyRedirect>>>;
    infoCheckoutRedirect: import("../store/types").Selectors<import("..").InfoCheckoutRedirect, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoCheckoutRedirect>>>;
    infoValidateEmail: import("../store/types").Selectors<import("..").InfoValidationEmail, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").InfoValidationEmail>>>;
    checkJob: import("../store/types").Selectors<import("..").JobCreditState, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").JobCreditState>>>;
    payoutsJob: import("../store/types").Selectors<import("..").Tally, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Tally>>>;
    jobCheckoutLink: import("../store/types").Selectors<import("..").RedirectURLs, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").RedirectURLs>>>;
    jobCompanyInfo: import("../store/types").Selectors<import("..").JobCompanyInfo, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").JobCompanyInfo>>>;
    exportJobPayouts: import("../store/types").Selectors<import("..").ExportCSV, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").ExportCSV>>>;
    tradeQuoteApprovalLead: import("../store/types").Selectors<import("..").Job, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").Job>>>;
    matchTradesLead: import("../store/types").Selectors<import("..").TradeSummary, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").TradeSummary>>>;
    connectTradesLead: import("../store/types").Selectors<import("..").TradeSummary, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").TradeSummary>>>;
    acceptedJobSummaryLead: import("../store/types").Selectors<import("..").LeadJobSummary, import("../types").StringIndexedObject<import("../store/types").GeneratedState<import("..").LeadJobSummary>>>;
}) => (() => CurrentUserHook);
