name: "publish-schema-packages"

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:

jobs:
  publish-schema-package-qa:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: "ubuntu-latest"
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CICD_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          message: Starting CI/CD build for `{{ env.GITHUB_REF_NAME }}`

      - uses: "actions/checkout@v3"

      - name: "setup node"
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: "generate typescript bindings"
        run: "make qa clean gen-frontend"

      - name: "build npm package"
        run: npm install && npm run build

      - name: "publish npm package"
        run: rm -rf .git/ && npm version $(npm view ks-schema version | awk 'BEGIN{FS=OFS="."} {$3+=1} 1') --force && npm publish --force --allow-same-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
