import { type Reducer } from '@reduxjs/toolkit';
import type { AuthState } from './slices/auth';
type ReducerMap<M> = {
    [K in keyof M]: Reducer<M[K]>;
};
export declare function createStore<PageKeys extends string, ExtraState = {}>(extraReducers?: ReducerMap<ExtraState>): import("@reduxjs/toolkit/dist/configureStore").ToolkitStore<{
    authUser: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").AuthUser>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    company: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Company>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    credit: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Credit>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    document: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Document>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    enterprise: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Enterprise>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    event: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Event>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoAuth: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoAuth>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoCompany: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoCompany>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoEntity: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoEntity>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoGhost: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoGhost>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoIP: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoIP>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoLead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoLead>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoOnboarding: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoOnboarding>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoQuery: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoQuery>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoSearch: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoSearch>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoStats: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoStats>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    job: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Job>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    lead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Lead>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    monitor: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Monitor>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    onboarding: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Onboarding>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    partner: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Partner>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    payment: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Payment>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    rate: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Rate>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    subscription: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Subscription>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    tradeSummary: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").TradeSummary>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    training: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Training>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    postCompanyBilling: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").RedirectURLs>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    getCompanyDirectorVerification: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoCompany>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    postCompanyDirectorVerification: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoCompany>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    postCompanyReferrals: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Referral>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    exportFcaApproved: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").ExportCSV>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoSession: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoSession>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoGetCache: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Cache>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoPutCache: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Cache>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoDeleteCache: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Cache>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoCustomer: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Customer>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoDirector: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").OwnerReport>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoEnterpriseRole: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").EnterpriseUserRole>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoEnterprise: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Enterprise>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoHealth: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Error>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoPartnerBranding: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoPartnerBranding>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoLegacyRedirect: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoLegacyRedirect>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoCheckoutRedirect: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoCheckoutRedirect>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoValidateEmail: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoValidationEmail>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    checkJob: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").JobCreditState>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    payoutsJob: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Tally>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    jobCheckoutLink: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").RedirectURLs>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    jobCompanyInfo: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").JobCompanyInfo>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    exportJobPayouts: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").ExportCSV>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    tradeQuoteApprovalLead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Job>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    matchTradesLead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").TradeSummary>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    connectTradesLead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").TradeSummary>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    acceptedJobSummaryLead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").LeadJobSummary>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    app: import("./slices/app").AppState<PageKeys>;
    auth: AuthState;
}, import("redux").AnyAction, import("@reduxjs/toolkit").MiddlewareArray<[import("@reduxjs/toolkit").ThunkMiddleware<{
    authUser: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").AuthUser>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    company: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Company>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    credit: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Credit>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    document: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Document>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    enterprise: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Enterprise>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    event: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Event>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoAuth: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoAuth>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoCompany: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoCompany>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoEntity: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoEntity>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoGhost: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoGhost>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoIP: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoIP>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoLead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoLead>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoOnboarding: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoOnboarding>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoQuery: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoQuery>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoSearch: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoSearch>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoStats: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoStats>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    job: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Job>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    lead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Lead>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    monitor: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Monitor>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    onboarding: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Onboarding>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    partner: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Partner>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    payment: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Payment>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    rate: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Rate>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    subscription: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Subscription>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    tradeSummary: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").TradeSummary>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    training: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Training>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    postCompanyBilling: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").RedirectURLs>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    getCompanyDirectorVerification: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoCompany>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    postCompanyDirectorVerification: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoCompany>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    postCompanyReferrals: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Referral>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    exportFcaApproved: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").ExportCSV>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoSession: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoSession>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoGetCache: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Cache>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoPutCache: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Cache>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoDeleteCache: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Cache>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoCustomer: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Customer>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoDirector: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").OwnerReport>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoEnterpriseRole: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").EnterpriseUserRole>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoEnterprise: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Enterprise>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoHealth: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Error>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoPartnerBranding: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoPartnerBranding>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoLegacyRedirect: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoLegacyRedirect>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoCheckoutRedirect: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoCheckoutRedirect>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    infoValidateEmail: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").InfoValidationEmail>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    checkJob: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").JobCreditState>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    payoutsJob: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Tally>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    jobCheckoutLink: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").RedirectURLs>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    jobCompanyInfo: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").JobCompanyInfo>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    exportJobPayouts: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").ExportCSV>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    tradeQuoteApprovalLead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").Job>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    matchTradesLead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").TradeSummary>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    connectTradesLead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").TradeSummary>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    acceptedJobSummaryLead: {
        ids: import("@reduxjs/toolkit").EntityId[];
        entities: import("@reduxjs/toolkit").Dictionary<import("..").LeadJobSummary>;
        error?: import("../types").ExtractedError;
        isSubmitting: boolean;
        hasFetched: boolean;
        fetchedList: boolean;
        chainedRequest: boolean;
        isLoading: boolean;
    };
    app: import("./slices/app").AppState<PageKeys>;
    auth: AuthState;
}, import("redux").AnyAction, undefined>]>>;
export type AuthSlice = {
    auth: AuthState;
};
export declare function createSelectors<State extends AuthSlice, Pages>(): {
    getAuth: (state: State) => AuthState;
    getUser: (state: State) => import("..").AuthUser;
    getFirebaseUser: (state: State) => import("@firebase/auth").User;
    getAuthIsLoading: (state: State) => boolean;
    getIsUserLoggedIn: (state: State) => boolean;
    getRoot: (state: State) => State;
    getApp: (state: State) => State["app"];
    getPathKey: (state: State) => import("./types").PathKey<Pages>;
    getIsLoading: (state: State) => boolean;
    authUser: import("./types").Selectors<import("..").AuthUser, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").AuthUser>>>;
    company: import("./types").Selectors<import("..").Company, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Company>>>;
    credit: import("./types").Selectors<import("..").Credit, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Credit>>>;
    document: import("./types").Selectors<import("..").Document, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Document>>>;
    enterprise: import("./types").Selectors<import("..").Enterprise, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Enterprise>>>;
    event: import("./types").Selectors<import("..").Event, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Event>>>;
    infoAuth: import("./types").Selectors<import("..").InfoAuth, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoAuth>>>;
    infoCompany: import("./types").Selectors<import("..").InfoCompany, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoCompany>>>;
    infoEntity: import("./types").Selectors<import("..").InfoEntity, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoEntity>>>;
    infoGhost: import("./types").Selectors<import("..").InfoGhost, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoGhost>>>;
    infoIP: import("./types").Selectors<import("..").InfoIP, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoIP>>>;
    infoLead: import("./types").Selectors<import("..").InfoLead, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoLead>>>;
    infoOnboarding: import("./types").Selectors<import("..").InfoOnboarding, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoOnboarding>>>;
    infoQuery: import("./types").Selectors<import("..").InfoQuery, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoQuery>>>;
    infoSearch: import("./types").Selectors<import("..").InfoSearch, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoSearch>>>;
    infoStats: import("./types").Selectors<import("..").InfoStats, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoStats>>>;
    job: import("./types").Selectors<import("..").Job, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Job>>>;
    lead: import("./types").Selectors<import("..").Lead, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Lead>>>;
    monitor: import("./types").Selectors<import("..").Monitor, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Monitor>>>;
    onboarding: import("./types").Selectors<import("..").Onboarding, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Onboarding>>>;
    partner: import("./types").Selectors<import("..").Partner, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Partner>>>;
    payment: import("./types").Selectors<import("..").Payment, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Payment>>>;
    rate: import("./types").Selectors<import("..").Rate, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Rate>>>;
    subscription: import("./types").Selectors<import("..").Subscription, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Subscription>>>;
    tradeSummary: import("./types").Selectors<import("..").TradeSummary, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").TradeSummary>>>;
    training: import("./types").Selectors<import("..").Training, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Training>>>;
    postCompanyBilling: import("./types").Selectors<import("..").RedirectURLs, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").RedirectURLs>>>;
    getCompanyDirectorVerification: import("./types").Selectors<import("..").InfoCompany, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoCompany>>>;
    postCompanyDirectorVerification: import("./types").Selectors<import("..").InfoCompany, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoCompany>>>;
    postCompanyReferrals: import("./types").Selectors<import("..").Referral, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Referral>>>;
    exportFcaApproved: import("./types").Selectors<import("..").ExportCSV, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").ExportCSV>>>;
    infoSession: import("./types").Selectors<import("..").InfoSession, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoSession>>>;
    infoGetCache: import("./types").Selectors<import("..").Cache, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Cache>>>;
    infoPutCache: import("./types").Selectors<import("..").Cache, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Cache>>>;
    infoDeleteCache: import("./types").Selectors<import("..").Cache, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Cache>>>;
    infoCustomer: import("./types").Selectors<import("..").Customer, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Customer>>>;
    infoDirector: import("./types").Selectors<import("..").OwnerReport, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").OwnerReport>>>;
    infoEnterpriseRole: import("./types").Selectors<import("..").EnterpriseUserRole, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").EnterpriseUserRole>>>;
    infoEnterprise: import("./types").Selectors<import("..").Enterprise, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Enterprise>>>;
    infoHealth: import("./types").Selectors<import("..").Error, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Error>>>;
    infoPartnerBranding: import("./types").Selectors<import("..").InfoPartnerBranding, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoPartnerBranding>>>;
    infoLegacyRedirect: import("./types").Selectors<import("..").InfoLegacyRedirect, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoLegacyRedirect>>>;
    infoCheckoutRedirect: import("./types").Selectors<import("..").InfoCheckoutRedirect, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoCheckoutRedirect>>>;
    infoValidateEmail: import("./types").Selectors<import("..").InfoValidationEmail, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").InfoValidationEmail>>>;
    checkJob: import("./types").Selectors<import("..").JobCreditState, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").JobCreditState>>>;
    payoutsJob: import("./types").Selectors<import("..").Tally, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Tally>>>;
    jobCheckoutLink: import("./types").Selectors<import("..").RedirectURLs, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").RedirectURLs>>>;
    jobCompanyInfo: import("./types").Selectors<import("..").JobCompanyInfo, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").JobCompanyInfo>>>;
    exportJobPayouts: import("./types").Selectors<import("..").ExportCSV, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").ExportCSV>>>;
    tradeQuoteApprovalLead: import("./types").Selectors<import("..").Job, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").Job>>>;
    matchTradesLead: import("./types").Selectors<import("..").TradeSummary, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").TradeSummary>>>;
    connectTradesLead: import("./types").Selectors<import("..").TradeSummary, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").TradeSummary>>>;
    acceptedJobSummaryLead: import("./types").Selectors<import("..").LeadJobSummary, import("../types").StringIndexedObject<import("./types").GeneratedState<import("..").LeadJobSummary>>>;
};
export {};
